branch-defaults:
  default:
    environment: Mysampleapplication-env
  master:
    environment: Mysampleapplication-env
environment-defaults:
  Mysampleapplication-env:
    branch: master
    repository: my-sample-project
global:
  application_name:  MySampleApplication
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Node.js running on
    64bit Amazon Linux 2017.03 v4.3.0
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
